// <auto-generated />
using System;
using EfCoreExample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCoreExample.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20200212133558_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfCoreExample.Models.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("EfCoreExample.Models.Registration", b =>
                {
                    b.OwnsOne("EfCoreExample.Models.Contact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("RegistrationId");

                            b1.Property<string>("LastName");

                            b1.HasKey("RegistrationId");

                            b1.ToTable("Registrations");

                            b1.HasOne("EfCoreExample.Models.Registration")
                                .WithOne("Contact")
                                .HasForeignKey("EfCoreExample.Models.Contact", "RegistrationId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
